### ISSUE TITLE
Default date_time skill version 0.2.2 does not work correclty in Italian

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-docker#25]
The skill does not load even if it is well installed. It works fine with version 
```
ovos-skill-date-time              0.2.3a5
```

**Comment by goldyfruit** [comment]
`ovos-docker` pre-build images are based on alpha releases which is why version `0.2.2` _(not alpha)_ will not work and which is the reason why `ovos-skill-data-time`  Docker pre-build image is based on the alpha release as well.

- https://github.com/OpenVoiceOS/ovos-docker/blob/dev/skills/skill-date-time/Dockerfile#L20
- https://hub.docker.com/r/smartgic/ovos-skill-date-time/tags
